=== CBenghi/Xbim.Xids/Xbim.InformationSpecifications.NewTests/bsFiles/ids_05.xsd
<!-- edited with XMLSpy v2022 (x64) (http://www.altova.com) by buildingSMART International Ltd. -->
<!-- January 25, 2022 - DRAFT  -->
<xs:schema xmlns:ids="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://standards.buildingsmart.org/IDS" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.5.3">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.w3.org/2001/XMLSchema-instance"/>
	<xs:element name="ids">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="info">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="copyright" type="xs:string" minOccurs="0"/>
							<xs:element name="version" type="xs:string" minOccurs="0"/>
							<xs:element name="ifcVersion">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="IFC2X3">
											<xs:annotation>
												<xs:documentation>
													<Label>IFC 2x3 - formal version numer 2.3.0.1</Label>
												</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="IFC4">
											<xs:annotation>
												<xs:documentation>
													<Label>IFC 4 - formal version numer 4.0.2.1</Label>
												</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="IFC4_3">
											<xs:annotation>
												<xs:documentation>
													<Label>IFC 4.3 - formal version numer 4.3.0</Label>
												</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="description" type="xs:string" minOccurs="0"/>
							<xs:element name="author" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[^@]+@[^\.]+\..+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="date" type="xs:date" minOccurs="0"/>
							<xs:element name="purpose" type="xs:string" minOccurs="0"/>
							<xs:element name="milestone" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="specifications">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="ids:specificationsType"/>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="entityType">
		<xs:sequence>
			<xs:element name="name" type="ids:idsValue"/>
			<xs:element name="predefinedType" type="ids:idsValue" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="idsValue">
		<xs:choice minOccurs="1">
			<!-- place for potential additional rules for idsValue -->
			<xs:element name="simpleValue" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="xs:restriction" minOccurs="1" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="classificationType">
		<xs:sequence>
			<xs:element name="value" type="ids:idsValue"/>
			<xs:element name="system" type="ids:idsValue" minOccurs="0"/>
			<xs:element name="instructions" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="applicabilityType">
		<xs:sequence>
			<xs:element name="entity" type="ids:entityType" minOccurs="0"/>
			<xs:element name="classification" type="ids:classificationType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="attribute" type="ids:attributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:propertyType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="material" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:materialType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="systemType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="href" type="xs:anyURI" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:sequence>
			<xs:element name="propertySet" type="ids:idsValue"/>
			<xs:element name="name" type="ids:idsValue"/>
			<xs:element name="ifcMeasure" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="IfcAreaDensityMeasure"/>
						<xs:enumeration value="IfcAreaMeasure"/>
						<xs:enumeration value="add more here..."/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="value" type="ids:idsValue"/>
			<xs:element name="instructions" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="attributeType">
		<xs:sequence>
			<xs:element name="name" type="ids:idsValue"/>
			<xs:element name="value" type="ids:idsValue"/>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="materialType">
		<xs:sequence>
			<xs:element name="value" type="ids:idsValue"/>
			<xs:element name="instructions" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="requirementsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="entity" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Make sure 'Name' value of requirements entity is the same as the 'applicability' node, or a wildcard (inclusive pattern).</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:entityType">
							<xs:attribute name="partOf" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="IfcAssembly"/>
										<xs:enumeration value="IfcGroup"/>
										<xs:enumeration value="IfcSystem"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="classification" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:classificationType">
							<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:attributeType">
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:propertyType">
							<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="material" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:materialType">
							<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="specificationType">
		<xs:sequence>
			<xs:element name="applicability" type="ids:applicabilityType"/>
			<xs:element name="requirements" type="ids:requirementsType"/>
			<xs:element name="instructions" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="use" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="required"/>
					<xs:enumeration value="optional"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="specificationsType">
		<xs:sequence>
			<xs:element name="specification" type="ids:specificationType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== CBenghi/Xbim.Xids/Xbim.InformationSpecifications.NewTests/bsFiles/IDS_Aedes_example.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ids:ids xmlns:ids="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS  ids_05.xsd">
    <ids:info>
        <ids:title>AedesUVIP-ILS Window use-case example</ids:title>
        <ids:version>1.0</ids:version>
    </ids:info>
    <ids:specifications>
        <ids:specification ifcVersion="IFC2X3" name="Beglazing" description="Glazing in a window" use="optional">
            <ids:applicability>
                <ids:entity>
                    <ids:name>
                        <ids:simpleValue>IfcWindow</ids:simpleValue>
                    </ids:name>
                    <ids:predefinedType>
						<ids:simpleValue>WINDOW</ids:simpleValue>
					</ids:predefinedType>
                </ids:entity>
                <ids:classification location="any">
					<ids:value>
						<xs:restriction>
							<xs:pattern value="31.2[0-9]"/>
						</xs:restriction>
					</ids:value>
				</ids:classification>
            </ids:applicability>
            <ids:requirements>
            </ids:requirements>
        </ids:specification>
    </ids:specifications>
</ids:ids>

=== CBenghi/Xbim.Xids/Xbim.InformationSpecifications.NewTests/bsFiles/IDS_aachen_example.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ids:ids xmlns:ids="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS  ids_05.xsd">   
    <ids:info>
        <ids:title>Examnple on use of attributes (for student research)</ids:title>
        <ids:copyright>buildingSMART International Ltd</ids:copyright>
        <ids:ifcversion>IFC2X3</ids:ifcversion>
        <ids:date>2022-01-12</ids:date>
    </ids:info>
    <ids:specifications>
        <ids:specification name="Aachen test" use="required">
            <ids:applicability>
                <ids:entity>
                    <ids:name>
                        <ids:simpleValue>IfcOpeningElement</ids:simpleValue>
                    </ids:name>
                </ids:entity>
            </ids:applicability>
            <ids:requirements>
                <ids:attribute location="instance">
                    <ids:name>
                        <ids:simpleValue>name</ids:simpleValue>
                    </ids:name>
                    <ids:value>
                        <xs:restriction>
                            <xs:pattern value="^(Wanddurchbruch.*|Deckendurchbruch.*)"/>
                        </xs:restriction>
                    </ids:value>
                </ids:attribute>
            </ids:requirements>
        </ids:specification>
    </ids:specifications>
</ids:ids>
